GT-262: BFD: Fix Elf_Internal_ABIFlags_v0 accessor namespace clash
Fix:

../../bfd/libbfd.a(elfxx-nanomips.o): In function `bfd_mips_elf_swap_abiflags_v0_in':
.../bfd/elfxx-nanomips.c:186: multiple definition of `bfd_mips_elf_swap_abiflags_v0_in'
../../bfd/libbfd.a(elfxx-mips.o):.../bfd/elfxx-mips.c:2744: first defined here
../../bfd/libbfd.a(elfxx-nanomips.o): In function `bfd_mips_elf_swap_abiflags_v0_out':
.../bfd/elfxx-nanomips.c:206: multiple definition of `bfd_mips_elf_swap_abiflags_v0_out'
../../bfd/libbfd.a(elfxx-mips.o):.../bfd/elfxx-mips.c:2764: first defined here
collect2: error: ld returned 1 exit status
Makefile:325: recipe for target 'run' failed
make[2]: *** [run] Error 1

in an `--enable-targets=all' build.

	bfd/
	* elfxx-nanomips.c (bfd_mips_elf_swap_abiflags_v0_in): Rename
	to...
	(bfd_nanomips_elf_swap_abiflags_v0_in): ... this.
	(bfd_mips_elf_swap_abiflags_v0_out): Rename to...
	(bfd_nanomips_elf_swap_abiflags_v0_out): ... this.
	(_bfd_nanomips_elf_section_from_shdr): Update accordingly.

	include/
	* elf/nanomips.h (bfd_nanomips_elf_swap_abiflags_v0_in)
	(bfd_nanomips_elf_swap_abiflags_v0_out): New prototypes.