GT-262: GDB: Fix `mask_address_var' variable namespace clash
Fix:

nanomips-tdep.o:(.data+0x3b0): multiple definition of `mask_address_var'
mips-tdep.o:(.data+0x5b0): first defined here
collect2: error: ld returned 1 exit status
Makefile:2207: recipe for target 'gdb' failed
make[1]: *** [gdb] Error 1

in an `--enable-targets=all' build.

	gdb/
	* nanomips-tdep.c (mask_address_var): Make static.